### PR TITLE
PW-96 Add Required Styling to TextField

### PR DESCRIPTION
**Pull request by MMFane**
# What Was Changed

- Added a left-aligned red asterisk to TextField to show that a field is required

## Questions for the Team

- @HaleyWardo pointed out that the 'required' prop may be confused for validation. Can I get thoughts on a solution?
  - Idea: Change to "styleRequired" or similar
  - Idea: Add docs note that this is just visual and validation still needs to be done

# Screenshots

## Before
Screen Shot 2022-07-29 at 12 41 25 PM

## After
Screen Shot 2022-07-29 at 12 41 09 PM

### CODE REVIEW

**Comment by loscm** [comment]
Requested review from a random `@lifeomic/security` team member, @bishopb, due to term: **risk**.

This review is not blocking and is for broader awareness.  Consider if this change requires deeper security review and ask when it is necessary.

- [Automation](https://github.com/lifeomic/pr-security-flag-scanner/blob/master/src/lambdas/pr-security-flag-scanner/index.ts) | [#pr-flagged-sec-review](https://lifeomic.slack.com/messages/pr-flagged-sec-review)

**Comment by HaleyWardo** [comment]
My suggestion is that the prop be called `showRequiredLabel` or something along that - but I am curious as to what others think. As you mentioned in the description, `required` makes me think that this is a controlled input and validation would be handled. I think we need the prop name to be more specific.

**Comment by xdumaine** [comment]
I've definitely thought that adding `required` would do validation in the past, so good calling it out.

> Idea: Add docs note that this is just visual and validation still needs to be done

If you do this, just do it as a TSDoc on the property so it shows when doing autocomplete. TSDoc supports markdown in most editors so you can make it a bold node.

**Comment by MMFane** [comment]
> I've definitely thought that adding `required` would do validation in the past, so good calling it out.
> 
> > Idea: Add docs note that this is just visual and validation still needs to be done
> 
> If you do this, just do it as a TSDoc on the property so it shows when doing autocomplete. TSDoc supports markdown in most editors so you can make it a bold node.
> 
> Maybe _both_ a different prop name, and the TSDoc description.

Thanks Xander and Haley - I'll do both. I have a suspicion only documenting it will lead to some folks in a hurry missing this detail and might cause unexpected issues for them.

**Review by swain — APPROVED** [review]
Code LGTM. I'll leave design feedback to others :)

**Review by HaleyWardo — APPROVED** [review]

**Review by xdumaine — APPROVED** [review]

**Pull request merged**
