### PR TITLE
Add explicit children prop to prep for react-18

### PR DESCRIPTION
**Pull request by ynotdraw**
### Changes

- Add explicit `children` prop to prep for `react-18` type changes
  - https://twitter.com/dan_abramov/status/1512833611401150474?s=21&t=ZE1lLF3izIsZA43_TgTeKw
  - This should make our upgrade (when ready) a lot smoother

### CODE REVIEW

**Review by smolster — APPROVED** [review]
Looks great! Thanks for jumping on this!

**Review by evanheisler — APPROVED** [review]
Thanks for being proactive with this change. Its sure to prevent what would've otherwise been some head scratching time loss 👍

**Review by jkdowdle — APPROVED** [review]

**Comment by jkdowdle** [comment]
Was this done with that codemod? nice!

**Review by AClineff — APPROVED** [review]
🔥

**Pull request merged**
