### PR TITLE
Update to Storybook 7

### PR DESCRIPTION
**Pull request by MMFane**
# What’s New
## Several Breaking Changes
[see the migration guide for more details](https://storybook.js.org/docs/react/migration-guide)
- Now using Webpack5
- IE11 support discontinued
- Node 16 minimum
- Babel mode v7
- Start and build CLI binaries removed
- Some community add-ons might not work yet

## Formatting Updates
- [MDX1 upgraded to MDX2](https://mdxjs.com/blog/v2/)
- storiesOf support is fully discontinued - We had already upgraded to the Component Stories Format (CSF) thanks to [@nicolls1’s Storybook 6 upgrade](https://github.com/lifeomic/chroma-react/pull/301)
- CSF3 has been released. Look forward to a second PR updating our components to use its more streamlined formatting.
    - [Improved Type Safety](https://storybook.js.org/blog/improved-type-safety-in-storybook-7/)

### CODE REVIEW

**Review by swain — APPROVED** [review]
Nice!! Thanks for taking the time to keep this up to date.

Question: While this is a certainly a breaking change in _storybook_, does it really represent a breaking change in _chroma_? To me, seems like this PR will not modify consumer-facing behavior in any way, so maybe it can just be left as `docs:` rather than `docs!:`.

Not hugely important -- just throwing it out.

Approving b/c it's totally non-blocking. Again, thanks for taking the time! 🙏🏼

**Comment by shawnzhu** [comment]
closes #357

**Review by shawnzhu — APPROVED** [review]
LGTM

I created https://github.com/lifeomic/chroma-react/pull/371 to include docs build into PR & branch build checks

**Comment by MMFane** [comment]
> Question: While this is a certainly a breaking change in _storybook_, does it really represent a breaking change in _chroma_? To me, seems like this PR will not modify consumer-facing behavior in any way, so maybe it can just be left as `docs:` rather than `docs!:`.

Hey @swain ! Yeah, I wasn't 100% sure - what pushed me over to calling it a breaking change was that it requires Webpack5, but maybe that was overcautious? I'd love to understand better for future PRs

**Comment by swain** [comment]
@MMFane Sounds good. I'll move discussion to Slack :)

**Pull request merged**
