### PR TITLE
fix: Use palette for `<DayPicker` background hover color

### PR DESCRIPTION
**Pull request by dexterca**
Use palette for day background hover color vs. default `react-day-picker` color

BEFORE | AFTER
-- | --
Screen Shot 2022-06-21 at 3 26 57 PM | Screen Shot 2022-06-21 at 3 30 01 PM

### Keyboard focus

Screen Shot 2022-06-21 at 3 34 01 PM

### CODE REVIEW

**Comment by HaleyWardo** [comment]
Honestly, I can hardly see the hover color. At first glance, I thought you removed the color completely. Are we sure this change is accessible?

**Review by mstagg — APPROVED** [review]
If accessibility is a factor, just reduce the fade a bit to increase the contrast. Otherwise LGTM.

**Comment by dexterca** [comment]
@HaleyWardo a11y is not really a concern here as it's just a hover state. Keyboard users will get a separate state for keyboard focus (see above screenshot). I'm trying to keep the hover state subtle just like we do elsewhere in the Chrōma (e.g., table row hover).

**Comment by HaleyWardo** [comment]
> @HaleyWardo a11y is not really a concern here as it's just a hover state. Keyboard users will get a separate state for keyboard focus (see above screenshot). I'm trying to keep the hover state subtle just like we do elsewhere in Chrōma (e.g., table row hover). I did go ahead and add a little more contrast but it's more than other hover colors in Chrōma so we've lost some consistency there.

@dexterca I am more worried about the visual impaired (ex. colorblind) users since it was hard for me to even see the blue contrast. As long as the blue contrast meets the WCAG AA guidelines then we should be good!

**Review by HaleyWardo — APPROVED** [review]

**Pull request merged**
